import java.util.Random;

/**
 * Student name: WeiFeng Huang
 * Student number: 300185296
 * Point3D is a class store a particular Point(X,Y,Z)
 * It has attribute of clusterLabel, NoiseLabel.
 * Method: getter and setter for these attributes, setRgb, Distance and toString.
 */
public class Point3D {
    private double x;
    private double y;
    private double z;
    private double R;
    private double G;
    private double B;
    private int clusterLabel;

    private int NoiseLabel;

    /**
     * The constructor for class Point3D with three input parameter.
     * @param x x-coordinate
     * @param y y-coordinate
     * @param z z-coordinate
     * It initializes the NoiseLabel and clusterLabel to be 0.
     * Also, the color indicator R,G,B is set to 0.
     * For NoiseLabel,0 is undefined, 1 is label as noise by method
     * DBScanAlgorithm in class DBScan.
     * For clusterLabel, if both point(x,y,z) has same cluster with
     * particular eps and minPts(In class DBScan), their clusterLabel
     * would be same and labeled from DBScanAlgorithm.
     */
    public Point3D(double x, double y, double z) {
        this.x = x;
        this.y = y;
        this.z = z;
        R=0;
        G=0;
        B=0;
        NoiseLabel=0;
        clusterLabel=0;
    }

    public double getX() {
        return x;
    }

    public double getY() {
        return y;
    }

    public double getZ() {
        return z;
    }

    public double getR() {
        return R;
    }

    public double getG() {
        return G;
    }

    public double getB() {
        return B;
    }


    public int getClusterLabel(){
        return clusterLabel;
    }

    public void setClusterLabel(int label) {
        clusterLabel=label;
    }

    //0 is undefined 1 is label as noise
    public void setNoiseLabel(int s){
        NoiseLabel=s;
    }

    public int getNoiseLabel(){
        return NoiseLabel;
    }

    /**
     * method helps to set RGB
     * @param rgb a Double[] generated by rgbUpdate() in class DBSCan
     */
    public void setRgb(Double[] rgb){
        R=rgb[0];
        G=rgb[1];
        B=rgb[2];
    }


    /**
     * return the Euclidean distance between the input
     * point(x,y,z) and current point(x',y',z')
     * @param pt a point(x,y,z)
     * @return the Euclidean distance
     */
    public double distance(Point3D pt){
        return Math.sqrt(Math.pow(x-pt.x,2)+Math.pow(y-pt.y,2)+Math.pow(z-pt.z,2));
    }
    /**
     * method toString is implemented for testing.
     */
    @Override
    public String toString() {
        return "X is "+x+", Y is "+y+", Z is "+z+", ClusterLabel is "+clusterLabel;
    }
}
